package gui;

import data.ProductDA;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import model.ItemBasedProduct;
import model.Product;
import model.WeightBasedProduct;

/**
 *
 * @author Vukona-Maritz
 */
public class MainForm extends javax.swing.JFrame {

    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel addProductPanel;
    private javax.swing.JPanel viewSalesPanel;
    private javax.swing.JLabel statusBar;

    private void showPanel(String panelName) {
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, panelName);
    }

    public MainForm() {
        initComponents();
        mainPanel.add(panelHome, "Home");
        mainPanel.add(panelAddProduct, "Add");
        mainPanel.add(panelViewSales, "View");

        // --- Home panel content ---
        panelHome.setLayout(new BoxLayout(panelHome, BoxLayout.Y_AXIS));
        panelHome.setBorder(BorderFactory.createEmptyBorder(40, 20, 40, 20));

        JLabel lblWelcome = new JLabel("Welcome to Product Sales System", SwingConstants.CENTER);
        lblWelcome.setFont(new Font("SansSerif", Font.BOLD, 24));
        lblWelcome.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel lblAuthor = new JLabel("Developed by Vukona | Java Desktop App", SwingConstants.CENTER);
        lblAuthor.setFont(new Font("SansSerif", Font.ITALIC, 14));
        lblAuthor.setAlignmentX(Component.CENTER_ALIGNMENT);

        JTextArea txtDescription = new JTextArea(
                "This system allows you to:\n"
                + "- Add and categorize products\n"
                + "- View and filter sales\n"
                + "- Update prices and manage inventory"
        );
        txtDescription.setEditable(false);
        txtDescription.setFont(new Font("SansSerif", Font.PLAIN, 14));
        txtDescription.setAlignmentX(Component.CENTER_ALIGNMENT);
        txtDescription.setBackground(panelHome.getBackground());

        panelHome.add(lblWelcome);
        panelHome.add(Box.createVerticalStrut(20));
        panelHome.add(lblAuthor);
        panelHome.add(Box.createVerticalStrut(20));
        panelHome.add(txtDescription);

        // --- Toolbar icons ---
        btnToolbarHome.setIcon(new ImageIcon("icons/home.png"));
        btnToolbarAdd.setIcon(new ImageIcon("icons/add.png"));
        btnToolbarView.setIcon(new ImageIcon("icons/view.png"));
        btnToolbarClear.setIcon(new ImageIcon("icons/clear.png"));
        btnToolbarExit.setIcon(new ImageIcon("icons/exit.png"));

        // Optional: tooltips
        btnToolbarHome.setToolTipText("Go to Home");
        btnToolbarAdd.setToolTipText("Add a new product");
        btnToolbarView.setToolTipText("View sales records");
        btnToolbarClear.setToolTipText("Clear inputs and output");
        btnToolbarExit.setToolTipText("Exit application");

        // --- Start on Home page ---
        showPanel("Home");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panelAddProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radItemBasedProduct = new javax.swing.JRadioButton();
        radWeightBasedProduct = new javax.swing.JRadioButton();
        btnSale = new javax.swing.JButton();
        panelViewSales = new javax.swing.JPanel();
        btnViewItemBased = new javax.swing.JButton();
        btnViewSales = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnViewWeightBased = new javax.swing.JButton();
        btnUpdatePrice = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        toolBarMain = new javax.swing.JToolBar();
        btnToolbarHome = new javax.swing.JButton();
        btnToolbarAdd = new javax.swing.JButton();
        btnToolbarView = new javax.swing.JButton();
        btnToolbarClear = new javax.swing.JButton();
        btnToolbarExit = new javax.swing.JButton();
        lblStatusBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setLayout(new java.awt.CardLayout());

        panelAddProduct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Barcode No:");

        jLabel3.setText("Product name:");

        jLabel4.setText("Unit Price:");

        jLabel5.setText("Product weight:");

        jLabel6.setText("Manufacturer:");

        txtBarcode.setBackground(new java.awt.Color(255, 255, 255));

        txtProductName.setBackground(new java.awt.Color(255, 255, 255));

        txtUnitPrice.setBackground(new java.awt.Color(255, 255, 255));

        txtWeight.setBackground(new java.awt.Color(255, 255, 255));
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });

        txtManufacturer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Product Category");

        buttonGroup1.add(radItemBasedProduct);
        radItemBasedProduct.setText("Item Based Product");

        buttonGroup1.add(radWeightBasedProduct);
        radWeightBasedProduct.setText("Weight Based Product");

        btnSale.setText("Sale");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddProductLayout = new javax.swing.GroupLayout(panelAddProduct);
        panelAddProduct.setLayout(panelAddProductLayout);
        panelAddProductLayout.setHorizontalGroup(
            panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProductLayout.createSequentialGroup()
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAddProductLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel4))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUnitPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtWeight)
                        .addComponent(txtProductName)
                        .addComponent(txtBarcode)))
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radItemBasedProduct)
                            .addComponent(jLabel7)
                            .addComponent(radWeightBasedProduct)))
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelAddProductLayout.setVerticalGroup(
            panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProductLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radItemBasedProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radWeightBasedProduct)
                        .addGap(18, 18, 18)
                        .addComponent(btnSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(panelAddProduct, "card2");

        panelViewSales.setBackground(new java.awt.Color(153, 153, 153));
        panelViewSales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnViewItemBased.setText("View Item Based Products");
        btnViewItemBased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewItemBasedActionPerformed(evt);
            }
        });

        btnViewSales.setText("View Sales");
        btnViewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalesActionPerformed(evt);
            }
        });

        txtOutput.setBackground(new java.awt.Color(204, 204, 204));
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        btnViewWeightBased.setText("View Weight Based Products");
        btnViewWeightBased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWeightBasedActionPerformed(evt);
            }
        });

        btnUpdatePrice.setText("Update Price");
        btnUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewSalesLayout = new javax.swing.GroupLayout(panelViewSales);
        panelViewSales.setLayout(panelViewSalesLayout);
        panelViewSalesLayout.setHorizontalGroup(
            panelViewSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnViewSales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewItemBased, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewWeightBased, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelViewSalesLayout.setVerticalGroup(
            panelViewSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewSalesLayout.createSequentialGroup()
                .addGroup(panelViewSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewSalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewItemBased, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewWeightBased, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewSalesLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(panelViewSales, "card2");

        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        mainPanel.add(panelHome, "card4");

        toolBarMain.setRollover(true);

        btnToolbarHome.setText("Home");
        btnToolbarHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarHomeActionPerformed(evt);
            }
        });
        toolBarMain.add(btnToolbarHome);

        btnToolbarAdd.setText("Add");
        btnToolbarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarAddActionPerformed(evt);
            }
        });
        toolBarMain.add(btnToolbarAdd);

        btnToolbarView.setText("View");
        btnToolbarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarViewActionPerformed(evt);
            }
        });
        toolBarMain.add(btnToolbarView);

        btnToolbarClear.setText("Clear");
        btnToolbarClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarClearActionPerformed(evt);
            }
        });
        toolBarMain.add(btnToolbarClear);

        btnToolbarExit.setText("Exit");
        btnToolbarExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolbarExitActionPerformed(evt);
            }
        });
        toolBarMain.add(btnToolbarExit);

        lblStatusBar.setText("Ready");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(toolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(lblStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(478, Short.MAX_VALUE)
                    .addComponent(lblStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed

        if (!validateInputs()) {
            lblStatusBar.setText("Validation failed");
            return;
        }

        try {
            int barcode = Integer.parseInt(txtBarcode.getText().trim());
            String name = txtProductName.getText().trim();
            String category = radItemBasedProduct.isSelected() ? "IBP" : "WBP";
            String manufacturer = txtManufacturer.getText().trim();
            int unitPrice = Integer.parseInt(txtUnitPrice.getText().trim());
            double amountPaid;
            Product product;

            if (radItemBasedProduct.isSelected()) {
                amountPaid = unitPrice;
                product = new ItemBasedProduct(barcode, name, category, manufacturer, unitPrice, amountPaid);
            } else {
                int weight = Integer.parseInt(txtWeight.getText().trim());
                amountPaid = (unitPrice * weight) / 1000.0;
                product = new WeightBasedProduct(barcode, name, category, manufacturer, weight, unitPrice, amountPaid);
            }

            ProductDA.addProduct(product);
            txtOutput.setText("Product added successfully.");
            lblStatusBar.setText("Product added successfully");
        } catch (Exception e) {
            txtOutput.setText("Error: " + e.getMessage());
            lblStatusBar.setText("Error during sale");
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSaleActionPerformed

    private void btnViewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalesActionPerformed
        try {
            ArrayList<Product> products = ProductDA.returnAll();
            StringBuilder sb = new StringBuilder();
            double totalAmount = 0.0;

            for (Product p : products) {
                sb.append(p.toString()).append("\n");
                totalAmount += p.getAmountPaid();
            }

            txtOutput.setText(sb.toString());
            /*txtOutput.setText("Total Products: " + products.size());
            txtOutput.setText(String.format("Total Sales: %.2f", totalAmount));
             */
            lblStatusBar.setText("Loaded all sales");
        } catch (Exception e) {
            txtOutput.setText("Error: " + e.getMessage());
            lblStatusBar.setText("Error loading sales");
        }
    }//GEN-LAST:event_btnViewSalesActionPerformed

    private void btnViewItemBasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewItemBasedActionPerformed
        try {
            ArrayList<Product> products = ProductDA.returnAll();
            StringBuilder sb = new StringBuilder();
            double totalAmount = 0.0;

            for (Product p : products) {
                if (p instanceof ItemBasedProduct) {
                    sb.append(p.toString()).append("\n");
                    totalAmount += p.getAmountPaid();
                }
            }

            txtOutput.setText(sb.toString());
            /*txtOutput.setText("Item-Based Products: " + products.size());
            txtOutput.setText(String.format("Total Sales: %.2f", totalAmount));
             */
            lblStatusBar.setText("Filtered item-based products");
        } catch (Exception e) {
            txtOutput.setText("Error: " + e.getMessage());
            lblStatusBar.setText("Error filtering IBP");
        }
    }//GEN-LAST:event_btnViewItemBasedActionPerformed

    private void btnUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePriceActionPerformed
        try {
            String barcodeStr = JOptionPane.showInputDialog("Enter barcode number:");
            String percentStr = JOptionPane.showInputDialog("Enter percentage increase:");
            int barcode = Integer.parseInt(barcodeStr);
            int percentage = Integer.parseInt(percentStr);
            ProductDA.updatePrice(barcode, percentage);
            txtOutput.setText("Price updated successfully.");
        } catch (Exception e) {
            txtOutput.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdatePriceActionPerformed

    private void btnViewWeightBasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWeightBasedActionPerformed
        try {
            ArrayList<Product> products = ProductDA.returnAll();
            StringBuilder sb = new StringBuilder();
            double totalAmount = 0.0;

            for (Product p : products) {
                if (p instanceof WeightBasedProduct) {
                    sb.append(p.toString()).append("\n");
                    totalAmount += p.getAmountPaid();
                }
            }

            txtOutput.setText(sb.toString());

            lblStatusBar.setText("Filtered weight-based products");
        } catch (Exception e) {
            txtOutput.setText("Error: " + e.getMessage());
            lblStatusBar.setText("Error filtering WBP");
        }
    }//GEN-LAST:event_btnViewWeightBasedActionPerformed

    private void btnToolbarExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarExitActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            lblStatusBar.setText("Exiting...");
            System.exit(0);
        }
    }//GEN-LAST:event_btnToolbarExitActionPerformed

    private void btnToolbarClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarClearActionPerformed
        txtOutput.setText("");
        txtBarcode.setText("");
        txtProductName.setText("");
        txtManufacturer.setText("");
        txtWeight.setText("");
        txtUnitPrice.setText("");
        buttonGroup1.clearSelection();
        lblStatusBar.setText("Cleared inputs and output");
    }//GEN-LAST:event_btnToolbarClearActionPerformed

    private void btnToolbarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarAddActionPerformed
        showPanel("Add");
        lblStatusBar.setText("Add Product page opened");
    }//GEN-LAST:event_btnToolbarAddActionPerformed

    private void btnToolbarViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarViewActionPerformed

        showPanel("View");
        lblStatusBar.setText("View Sales page opened");

    }//GEN-LAST:event_btnToolbarViewActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnToolbarHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolbarHomeActionPerformed
        showPanel("Home");
        lblStatusBar.setText("Home page opened");
    }//GEN-LAST:event_btnToolbarHomeActionPerformed

    private boolean validateInputs() {
        if (txtBarcode.getText().trim().isEmpty()
                || txtProductName.getText().trim().isEmpty()
                || txtUnitPrice.getText().trim().isEmpty()
                || (!radItemBasedProduct.isSelected() && !radWeightBasedProduct.isSelected())) {
            JOptionPane.showMessageDialog(this, "Please fill all required fields and select a product type.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (radWeightBasedProduct.isSelected() && txtWeight.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter weight for Weight-Based Product.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            Integer.parseInt(txtBarcode.getText().trim());
            Integer.parseInt(txtUnitPrice.getText().trim());
            if (radWeightBasedProduct.isSelected()) {
                Integer.parseInt(txtWeight.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Barcode, Unit Price, and Weight must be numeric.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSale;
    private javax.swing.JButton btnToolbarAdd;
    private javax.swing.JButton btnToolbarClear;
    private javax.swing.JButton btnToolbarExit;
    private javax.swing.JButton btnToolbarHome;
    private javax.swing.JButton btnToolbarView;
    private javax.swing.JButton btnUpdatePrice;
    private javax.swing.JButton btnViewItemBased;
    private javax.swing.JButton btnViewSales;
    private javax.swing.JButton btnViewWeightBased;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatusBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAddProduct;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelViewSales;
    private javax.swing.JRadioButton radItemBasedProduct;
    private javax.swing.JRadioButton radWeightBasedProduct;
    private javax.swing.JToolBar toolBarMain;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
